import { ProjectType } from "../types/Project";

export default [
  {
    title: "SpendSense",
    description: `A personal finance reflection app I built after realizing I wanted more than charts and budget totals. I designed a full-stack workflow for importing transactions, detecting duplicates, learning merchant-level categorization over time, and generating AI reflections that feel actionable, supportive, and grounded in real spending behavior.`,
    tags: [
      "Next.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "AI",
      "CSV Parsing",
    ],
    liveLink: "https://spendsense-five.vercel.app/",
    githubLink: "https://github.com/LataniaReece/SpendSense",
    image: "/assets/projectImgs/spendsense-dashboard.png",
    featured: true,
  },
  {
    title: "Recipe Haven",
    description: `A recipe discovery app built to make browsing, saving, and returning to meals feel more seamless. I combined real-time recipe search with authenticated favorites so the experience feels closer to a product someone could actually rely on.`,
    tags: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Edamam API",
      "Supabase",
      "PostgreSQL",
      "NextAuth",
      "Google Authentication",
    ],
    liveLink: "https://recipe-nextjs-app.vercel.app/",
    githubLink: "https://github.com/LataniaReece/recipe-haven",
    image: "/assets/projectImgs/recipehaven.png",
  },
  {
    title: "Blog Fullstack App",
    description: `A full-stack blogging platform where I focused on the coordination between frontend experience and backend data flow. The project gave me space to work through patterns around API design, state management, and rendering a responsive interface that still feels polished and intentional.`,
    tags: [
      "Node",
      "PostgreSQL",
      "TypeScript",
      "React",
      "Redux Toolkit",
      "Tests",
      "Framer Motion",
    ],
    liveLink: "https://blog-fullstack-app-ui.vercel.app/",
    githubLink: "https://github.com/LataniaReece/blog_fullstack_app",
    image: "/assets/projectImgs/blogFullstack.png",
  },
  {
    title: "Notes App",
    description: `A notes app built around the everyday need to capture and organize information without friction. I focused on creating a cleaner editing experience with rich text support and a UI that stays lightweight enough for quick, repeated use.`,
    tags: [
      "React",
      "JavaScript",
      "TypeScript",
      "Redux Toolkit",
      "Playwright",
      "Unit Tests",
    ],
    liveLink: "https://latania-notesapp.netlify.app",
    githubLink: "https://github.com/LataniaReece/Notes-App",
    image: "/assets/projectImgs/notesApp.png",
  },
] as ProjectType[];
